### ISSUE TITLE
Show comment in `lsmac` output

### ISSUE THREAD

**Issue by marr** [specious/osxutils#3]
I see there is a `getfcomment` which displays comment metadata about files and directories. Would it be possible to update `lsmac` to output that comment? 

Thanks,
Dave

**Comment by specious** [comment]
According to Wikipedia:

> The Unix philosophy emphasizes building simple, short, clear, modular, and extensible code that can be easily maintained and repurposed by developers other than its creators.

Article: https://en.wikipedia.org/wiki/Unix_philosophy

The `getfcomment` utility focuses on displaying comment metadata.  I would be careful about duplicating the same functionality in `lsmac`.  If you are interested in extending `lsmac` to optionally display comment metadata, perhaps via a `-C, --comment` flag, I would at the very least recommend extracting the implementation of `getfcomment` into a library to be shared between the two utilities, to avoid code duplication.
