### ISSUE TITLE
brew: conflicts

### ISSUE THREAD

**Issue by JayBrown** [specious/osxutils#5]
osxutil has some brew installation conflicts with **leptonica** (`fileinfo`), **trash** (`trash`), and **wiki** (`wiki`).

Maybe it would be wise to change e.g.

1. fileinfo > finfo, getinfo, getfinfo
2. trash > mvtrash
3. wiki > swiki

or something similar. To be fair: if you have the osxutils, you don't need the standalone `trash` program, so renaming isn't really necessary for no. 2.

**Comment by specious** [comment]
Thanks for bringing this up!

It has been mentioned that naming things is one of the hardest things in software development.  Your suggestions are on point.

**Comment by specious** [comment]
I renamed:

* `wiki` -> `wikipedia` (b0f190917014ac238db1a3f7e20c7eb74c43ca05)
* `trash` -> `mvtrash` (f91ff91ce9147e8ae0b4e48a73d75af6109c8e23)
* `fileinfo` -> `finfo` (f91ff91ce9147e8ae0b4e48a73d75af6109c8e23)

I hope this doesn't result in any new name collisions.

**Comment by JayBrown** [comment]
There are definitely no conflicts with any formula names. Can't say about actual executables distributed within those formulae. We'll see. :)

**Comment by specious** [comment]
I'm closing this issue: https://github.com/Homebrew/homebrew-core/commit/d97a2be7bc979b9341123c8fb23b21e4888b88e7
